### ISSUE TITLE
registration fiedls

### ISSUE THREAD

**Issue by thejmazz** [thejmazz/UofTBiohacks#18]
- Email
- Username
- First name
- Last name
- ADD: College
- POST: make it a text field
- University
- ~~Student Number~~
- Year of Study
- How did you hear about this event?
- Coding Background (take out vim option)
- Github
- REMOVE: questions? (we don’t wanna answer questions)
- REMOVE: Like to see question (We aren’t taking requests)
- Tell us about yourself
- REMOVE: mentor question
- REMOVE: Would you like to be automatically joined to the group
- Password
- Confirm Password
- ADD: Upload resume if possible, if not email us at bcbbiohacks2018@gmail.com

- If you are interested in Volunteering: link (update to the one on homepage, `https://goo.gl/forms/V3ujQb3Wt1qNXMYr1`)

**Comment by ACalza** [comment]
Captcha and resume to be finished
